final List<Map<String, dynamic>> dishes = [
  // ================= VEG =================
  {'name': 'Veg Biryani', 'price': 180, 'category': 'Veg'},
  {'name': 'Paneer Butter Masala', 'price': 220, 'category': 'Veg'},
  {'name': 'Mushroom Fry', 'price': 190, 'category': 'Veg'},
  {'name': 'Paneer Tikka', 'price': 210, 'category': 'Veg'},
  {'name': 'Veg Korma', 'price': 200, 'category': 'Veg'},
  {'name': 'Aloo Gobi', 'price': 160, 'category': 'Veg'},
  {'name': 'Veg Fried Rice', 'price': 170, 'category': 'Veg'},
  {'name': 'Veg Pulao', 'price': 160, 'category': 'Veg'},
  {'name': 'Palak Paneer', 'price': 210, 'category': 'Veg'},
  {'name': 'Chole Masala', 'price': 180, 'category': 'Veg'},
  {'name': 'Rajma Curry', 'price': 170, 'category': 'Veg'},
  {'name': 'Veg Kofta', 'price': 200, 'category': 'Veg'},
  {'name': 'Kadai Paneer', 'price': 220, 'category': 'Veg'},
  {'name': 'Mix Veg Curry', 'price': 180, 'category': 'Veg'},
  {'name': 'Stuffed Capsicum', 'price': 190, 'category': 'Veg'},

  // ================= NON-VEG =================
  {'name': 'Chicken Biryani', 'price': 250, 'category': 'Non-Veg'},
  {'name': 'Mutton Rogan Josh', 'price': 350, 'category': 'Non-Veg'},
  {'name': 'Fish Fry', 'price': 280, 'category': 'Non-Veg'},
  {'name': 'Chicken 65', 'price': 230, 'category': 'Non-Veg'},
  {'name': 'Butter Chicken', 'price': 260, 'category': 'Non-Veg'},
  {'name': 'Chicken Curry', 'price': 240, 'category': 'Non-Veg'},
  {'name': 'Mutton Biryani', 'price': 360, 'category': 'Non-Veg'},
  {'name': 'Fish Curry', 'price': 260, 'category': 'Non-Veg'},
  {'name': 'Egg Curry', 'price': 180, 'category': 'Non-Veg'},
  {'name': 'Chicken Fried Rice', 'price': 220, 'category': 'Non-Veg'},
  {'name': 'Chicken Noodles', 'price': 210, 'category': 'Non-Veg'},
  {'name': 'Grilled Chicken', 'price': 280, 'category': 'Non-Veg'},
  {'name': 'Chicken Lollipop', 'price': 240, 'category': 'Non-Veg'},
  {'name': 'Prawn Masala', 'price': 300, 'category': 'Non-Veg'},
  {'name': 'Chicken Kebab', 'price': 230, 'category': 'Non-Veg'},

  // ================= SOUTH INDIAN =================
  {'name': 'Idli', 'price': 40, 'category': 'South Indian'},
  {'name': 'Vada', 'price': 50, 'category': 'South Indian'},
  {'name': 'Plain Dosa', 'price': 60, 'category': 'South Indian'},
  {'name': 'Masala Dosa', 'price': 80, 'category': 'South Indian'},
  {'name': 'Onion Dosa', 'price': 90, 'category': 'South Indian'},
  {'name': 'Pongal', 'price': 70, 'category': 'South Indian'},
  {'name': 'Uttapam', 'price': 80, 'category': 'South Indian'},
  {'name': 'Upma', 'price': 60, 'category': 'South Indian'},
  {'name': 'Rava Dosa', 'price': 90, 'category': 'South Indian'},
  {'name': 'Set Dosa', 'price': 80, 'category': 'South Indian'},
  {'name': 'Curd Rice', 'price': 70, 'category': 'South Indian'},
  {'name': 'Lemon Rice', 'price': 70, 'category': 'South Indian'},
  {'name': 'Tomato Rice', 'price': 80, 'category': 'South Indian'},
  {'name': 'Sambar Rice', 'price': 90, 'category': 'South Indian'},
  {'name': 'Rasam Rice', 'price': 80, 'category': 'South Indian'},

  // ================= CHINESE =================
  {'name': 'Veg Manchurian', 'price': 180, 'category': 'Chinese'},
  {'name': 'Gobi Manchurian', 'price': 190, 'category': 'Chinese'},
  {'name': 'Chicken Manchurian', 'price': 220, 'category': 'Chinese'},
  {'name': 'Veg Noodles', 'price': 170, 'category': 'Chinese'},
  {'name': 'Schezwan Fried Rice', 'price': 190, 'category': 'Chinese'},
  {'name': 'Chicken Schezwan Noodles', 'price': 220, 'category': 'Chinese'},
  {'name': 'Paneer Manchurian', 'price': 210, 'category': 'Chinese'},
  {'name': 'Spring Rolls', 'price': 160, 'category': 'Chinese'},
  {'name': 'Chilli Chicken', 'price': 230, 'category': 'Chinese'},
  {'name': 'Hot Garlic Noodles', 'price': 190, 'category': 'Chinese'},
  {'name': 'American Chopsuey', 'price': 200, 'category': 'Chinese'},
  {'name': 'Veg Hakka Noodles', 'price': 180, 'category': 'Chinese'},
  {'name': 'Chicken Fried Rice', 'price': 220, 'category': 'Chinese'},
  {'name': 'Sweet Corn Soup', 'price': 120, 'category': 'Chinese'},
  {'name': 'Hot & Sour Soup', 'price': 130, 'category': 'Chinese'},

  // ================= FAST FOOD =================
  {'name': 'Veg Burger', 'price': 90, 'category': 'Fast Food'},
  {'name': 'Chicken Burger', 'price': 120, 'category': 'Fast Food'},
  {'name': 'French Fries', 'price': 80, 'category': 'Fast Food'},
  {'name': 'Veg Sandwich', 'price': 70, 'category': 'Fast Food'},
  {'name': 'Grilled Sandwich', 'price': 90, 'category': 'Fast Food'},
  {'name': 'Chicken Sandwich', 'price': 110, 'category': 'Fast Food'},
  {'name': 'Veg Pizza', 'price': 180, 'category': 'Fast Food'},
  {'name': 'Chicken Pizza', 'price': 220, 'category': 'Fast Food'},
  {'name': 'Cheese Pizza', 'price': 200, 'category': 'Fast Food'},
  {'name': 'Veg Wrap', 'price': 100, 'category': 'Fast Food'},
  {'name': 'Chicken Wrap', 'price': 130, 'category': 'Fast Food'},
  {'name': 'Pasta Alfredo', 'price': 190, 'category': 'Fast Food'},
  {'name': 'Pasta Arrabiata', 'price': 180, 'category': 'Fast Food'},
  {'name': 'Garlic Bread', 'price': 90, 'category': 'Fast Food'},
  {'name': 'Cheese Balls', 'price': 120, 'category': 'Fast Food'},

  // ================= DESSERTS =================
  {'name': 'Gulab Jamun', 'price': 60, 'category': 'Desserts'},
  {'name': 'Rasgulla', 'price': 60, 'category': 'Desserts'},
  {'name': 'Ice Cream Vanilla', 'price': 70, 'category': 'Desserts'},
  {'name': 'Ice Cream Chocolate', 'price': 80, 'category': 'Desserts'},
  {'name': 'Brownie', 'price': 120, 'category': 'Desserts'},
  {'name': 'Chocolate Cake', 'price': 140, 'category': 'Desserts'},
  {'name': 'Fruit Salad', 'price': 90, 'category': 'Desserts'},
  {'name': 'Carrot Halwa', 'price': 100, 'category': 'Desserts'},
  {'name': 'Payasam', 'price': 90, 'category': 'Desserts'},
  {'name': 'Kulfi', 'price': 80, 'category': 'Desserts'},

  // ================= DRINKS =================
  {'name': 'Coca Cola', 'price': 40, 'category': 'Drinks'},
  {'name': 'Pepsi', 'price': 40, 'category': 'Drinks'},
  {'name': 'Sprite', 'price': 40, 'category': 'Drinks'},
  {'name': 'Fanta', 'price': 40, 'category': 'Drinks'},
  {'name': 'Fresh Lime Soda', 'price': 60, 'category': 'Drinks'},
  {'name': 'Mint Lime Juice', 'price': 70, 'category': 'Drinks'},
  {'name': 'Orange Juice', 'price': 80, 'category': 'Drinks'},
  {'name': 'Water Bottle', 'price': 20, 'category': 'Drinks'},
  {'name': 'Cold Coffee', 'price': 90, 'category': 'Drinks'},
  {'name': 'Milk Shake', 'price': 100, 'category': 'Drinks'},

  // ================= BEVERAGES =================
  {'name': 'Hot Coffee', 'price': 50, 'category': 'Beverages'},
  {'name': 'Masala Tea', 'price': 30, 'category': 'Beverages'},
  {'name': 'Hot Chocolate', 'price': 120, 'category': 'Beverages'},
  {'name': 'Green Tea', 'price': 40, 'category': 'Beverages'},
  {'name': 'Black Coffee', 'price': 60, 'category': 'Beverages'},
];